baseURL = 'https://marinagrunder.github.io/'
locale = 'de-CH'
title = 'Marina Grunder'
defaultContentLanguage = 'de'
disableKinds = [ 'taxonomy', 'term' ]
enableGitInfo = true

[params]
    [params.copyNotice]
        baseYear = 2026
        author = 'Marina Grunder'
        noticeText = 'Alle Inhalte sind unter CC BY-SA 4.0 lizensiert, ausser anderweitig angegeben.'
